import Navbar from "../Navbar/Navbar";

export default function Home() {
  return (
    <>
      <Navbar />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      <div id="wedding">Wedding</div>
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      <div id="about">About</div>
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      <div id="contact">Contact</div>
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      Something <br />
      The End
    </>
  );
}
